// LEVEL I endpoints;

GET http://localhost:8080/api/library/book/list

###

GET http://localhost:8080/api/library/book/3

###

GET http://localhost:8080/api/library/book/list?author=repetitiveAuthor

###

GET http://localhost:8080/api/library/book/list?category=repetitionCategory

###

GET http://localhost:8080/api/library/book/list?category=repetitionCategory&limit=10

###

POST http://localhost:8080/api/library/book
Content-Type: application/json

{
    "category": "horror",
    "author": "Foo",
    "title": "Bar",
    "price": "25.10"
}



//Level II endpoints;
###

POST http://localhost:8080/api/bookstore/login
Content-Type: application/json

{
    "username": "root",
    "password": "root_pass"
}

### authorized request

GET http://localhost:8080/api/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTUzMzYzMjc1NCwiZXhwIjoxNTMzNjY4NzU0fQ.c23ipS8TsKAUGkQ8eXNEY5i6-cAlmgKxEXPFDlgTxJQ

### unauthorized request

GET http://localhost:8080/api/hello

###

POST http://localhost:8080/api/bookstore/login
Content-Type: application/json

{
    "username": "hello",
    "password": "hello_pass"
}

###