POST http://localhost:8080/bookstore/login
Content-Type: application/json

{
    "username": "root",
    "password": "root"
}

###

POST http://localhost:8080/bookstore/login

###

GET http://localhost:8080/bookstore/book/list
Authorization: {place to token}

###

POST http://localhost:8080/bookstore/book
Content-Type: application/json
Authorization: {place to token}

{
    "category": "novel",
    "author": "Tolstoy A.N.",
    "title": "War and Piece",
    "price": "99.900"
}

###