POST http://localhost:8080/itcompany/login

###

GET http://localhost:8080/itcompany/list
Authorization: {place to token}

###

GET http://localhost:8080/itcompany/3
Authorization: {place to token}

###

POST http://localhost:8080/itcompany
Content-Type: application/json
Authorization: {place to token}

{
    "firstName": "Emma",
    "lastName": "Tomphson",
    "email": "emmaTom@gmail.com",
    "career": "Project Manager",
    "skills": ["Scrum", "Agile"]
}

###

PUT http://localhost:8080/itcompany/11
Content-Type: application/json
Authorization: {place to token}

{
    "firstName": "Emma",
    "lastName": "Tomphson",
    "email": "emmaTomphson@gmail.com",
    "career": "Developer",
    "skills": ["Java", "Spring", "Scala"]
}

###

DELETE http://localhost:8080/itcompany/11
Authorization: {place to token}

###

GET http://localhost:8080/itcompany/list?firstName=Linda
Authorization: {place to token}

###

GET http://localhost:8080/itcompany/list?email=blackus@mail.org
Authorization: {place to token}

###

GET http://localhost:8080/itcompany/list?skills=Java (web)
Authorization: {place to token}

###