POST http://localhost:8080/api/itcompany/login

###

GET http://localhost:8080/api/itcompany/list
Authorization: {place to token}

###

GET http://localhost:8080/api/itcompany/3
Authorization: {place to token}

###

POST http://localhost:8080/api/itcompany
Authorization: {place to token}
Content-Type: application/json

{
    "firstName": "Emma",
    "lastName": "Tomphson",
    "email": "emmaTom@gmail.com",
    "career": "Project Manager",
    "skills": ["Scrum", "Agile"]
}

###

PUT http://localhost:8080/api/itcompany/3
Authorization: {place to token}
Content-Type: application/json

{
    "firstName": "Emma",
    "lastName": "Tomphson",
    "email": "emmaTomphson@gmail.com",
    "career": "Developer",
    "skills": ["Java", "Spring", "Scala"]
}

###

DELETE http://localhost:8080/api/itcompany/3
Authorization: {place to token}

###

GET http://localhost:8080/api/itcompany/test?hello=world&limit=10
Authorization: {place to token}

###

GET http://localhost:8080/api/itcompany/list?email=egestas.rhoncus.Proin@massaQuisqueporttitor.org
Authorization: {place to token}

###