
GET http://localhost:8080/api/library/book/list

###

GET http://localhost:8080/api/library/book/3

###

GET http://localhost:8080/api/library/book/list?author=repetitiveAuthor

###

GET http://localhost:8080/api/library/book/list?category=repetitionCategory

###

GET http://localhost:8080/api/library/book/list?category=repetitionCategory&limit=2

###

POST http://localhost:8080/api/library/book
Content-Type: application/json

{
    "category": "horror",
    "author": "Steven King",
    "title": "The Talisman",
    "price": "25.10"
}

###

PUT http://localhost:8080/api/library/book/10
Content-Type: application/json

{
    "category": "horror",
    "author": "Steven Ling",
    "title": "The Talisman",
    "price": "39.99"
}

###

DELETE http://localhost:8080/api/library/book/9

###